version: '2'

services:

  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/lib/docker/volumes/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
  
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    restart: always
    cap_add: NET_ADMIN
    ports:
      - 80:80
      - 443:443
    environment:
      PUID: 1000
      GUID: 1000
      TZ: Europe/London
      URL: mydomain.com
      SUBDOMAINS: wildcard
      VALIDATION: dns
      DNSPLUGIN: cloudflare
      ONLY_SUBDOMAINS: false
      EXTRA_DOMAINS: myotherdomain.com mythirddomain.com myfourthdomain.com
    volumes:
      - /var/lib/docker/volumes/letsencrypt:/config


  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: mydb_user
      MYSQL_PASSWORD: mydb_password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - /var/lib/docker/volumes/mysql:/var/lib/mysql

  wordpress:
    image: wordpress
    container_name: wordpress
    depends_on:
      - letsencrypt
      - db
    restart: always
    ports:
      - 81:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: faraday_user
      WORDPRESS_DB_PASSWORD: faraday_password
      WORDPRESS_DB_NAME: faraday
    volumes:
      - /var/lib/docker/volumes/wordpress:/var/www/html
